language: java
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: J//nh3ja6Gbpypdze+kR/GGOyuF8vN2o0dReb4qH6s4wqM2ptZrnKf1rhFhwpcjWFuBabYOOHG2iVeRX9XglcdeNrAAh/2YTROZ7p5LoYwVn3o5ktizkypAX2ldrso3YxwHv06kiQkEt+hVA92OKpMtTYWTtAC/SyLRao5o3RPiZ8tKSQ332rc7gdu6SrgxcnwlCoqj+97yfsuT6ncYefYsMny4viiFkE6S0PTVeHzMpd6K7lKIc1TxW30Gd36thyra9OmmT+L/8EBifsh43WBX+7K35CSMrHe9klWVaF0Hf/VLRaUJZA+SqbHGyUvzG1O+DN3FgFFqWQF8f2gOWOSyepUQqOFsODLUW9Jyf9xT8OOxvQwS2n6K6L+dhGrqy4evu0Dc0XwIGMphH8RTlbiDv6Y12ee28TCyfACpewDrBEbh/7UGuKOUW/YSHoZAHyLyjXmwtdanS9RrO8pCWiAsFLpkSUsUAX+ZOA2Hrh02G/BudBMUR2w5Xb8jBbh9t2f7mWFOvDcyNvkyoQVOH0gYYZUkEJMJ7bE2GOy7XhySm2Eu2FunusiMigFh2NSnnPwPH5cnEu+WmK3kR+/iEKmM9GZEB15Mv25W3HGnI9s+gbrDu+hPcBGvgfPZhPtmnOFRp+Drj/yJPpwjkZj0IY9bkcpiOFMBzzLxiHtt6Y1M=
